spring:
  profiles:
    active: dev  # 默认使用 dev 配置，生产环境可以手动修改或通过环境变量设置

aliyun:
  oss:
    endpoint: "${ALIYUN_OSS_ENDPOINT}"
    access-key-id: "${ALIYUN_OSS_ACCESS_KEY_ID}"
    access-key-secret: "${ALIYUN_OSS_ACCESS_KEY_SECRET}"
    bucket-name: "${ALIYUN_OSS_BUCKET_NAME}"

serverchan:
  token: "${SERVER_CHAN_KEY}"

