aliyun:
  oss:
    endpoint: "${ALIYUN_OSS_ENDPOINT}"
    access-key-id: "${ALIYUN_OSS_ACCESS_KEY_ID}"
    access-key-secret: "${ALIYUN_OSS_ACCESS_KEY_SECRET}"
    bucket-name: "${ALIYUN_OSS_BUCKET_NAME}"

serverchan:
  token: "${SERVER_CHAN_KEY}"

