spring:
  profiles:
    active: dev  # default using dev env
  datasource:
    url: ${AIVEN_MYSQL_URL}
    username: ${AIVEN_MYSQL_USERNAME}
    password: ${AIVEN_MYSQL_PASSWORD}
    driver-class-name: ${AIVEN_MYSQL_DRIVER_CLASSNAME}
    hikari:
      minimum-idle: 1                  # Create 1 connection at startup and keep them ready
      maximum-pool-size: 3            # Maximum number of connections in the pool
      idle-timeout: 1800000             # Release an idle connection if it’s not used for 30 minutes (ms)
      max-lifetime: 3600000            # Maximum lifetime of a connection is 1 hour (forcefully recycled, in ms)
      keepalive-time: 300000           # Send a keep-alive query every 5 minutes to keep connections alive (ms)



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # TODO: need to print to the log file
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    endpoint: "${ALIYUN_OSS_ENDPOINT}"
    access-key-id: "${ALIYUN_OSS_ACCESS_KEY_ID}"
    access-key-secret: "${ALIYUN_OSS_ACCESS_KEY_SECRET}"
    bucket-name: "${ALIYUN_OSS_BUCKET_NAME}"

okta:
  client-id: "${OKTA_CLIENT_ID}"
  client-secret: "${OKTA_CLIENT_SECRET}"
  redirect-uri: "${OKTA_REDIRECT_URI}"
  domain: "${OKTA_DOMAIN}"
  authServer: "${OKTA_AUTH_SERVER}"

serverchan:
  token: "${SERVER_CHAN_KEY}"

